version: '3.8'

services:
  weatherapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_API_URL=${WEATHER_API_URL}
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: "redis:5.0-alpine"
    ports:
      - "6379:6379"